zed_topics:
  zed_depth_map: "/zed2i/zed_node/depth/depth_registered"
  zed_point_clouds: "/zed2i/zed_node/point_cloud/cloud_registered"
  camera_image_color: '/zed2i/zed_node/rgb/image_rect_color'
  depth_camera_info: '/zed2i/zed_node/depth/camera_info'
  color_camera_info: '/zed2i/zed_node/left/camera_info'


  
